### ISSUE TITLE
Optimize SQL query

### ISSUE THREAD

**Issue by yaroslavr-itd** [paket-core/router#11]
SQL query for selecting available for couriering packages may be optimized.
If all event types will be known then logic for selecting available packages may be changed to:
`if last_event_type == 'launched' or 'delegate required' then package available`

**Comment by israellevin** [comment]
You are right. Current SQL is not just sub-optimal, it's lacking in logic and it's barely readable. And since we are moving event names to constants, this improvement will be both easy and recommended.

**Comment by yaroslavr-itd** [comment]
Done in [cf2d160](https://github.com/paket-core/router/commit/cf2d160bb5d7f4fe01aa64661c594965e50b1a3c)
