### ISSUE TITLE
Move events names to constants

### ISSUE THREAD

**Issue by yaroslavr-itd** [paket-core/router#12]
For the purpose of comfortable usage and preventing typos, need to move events names to constants.

**Comment by yaroslavr-itd** [comment]
Done in [6d95f37](https://github.com/paket-core/router/commit/6d95f37e04f5c110dff510308ad8172c17f4b198)

**Comment by israellevin** [comment]
@yaroslavr-itd , I have turned on an automation option, so issues should move automatically to the done column when you close them.
