### ISSUE TITLE
Add a unified short package ID

### ISSUE THREAD

**Issue by israellevin** [paket-core/router#14]
Add a field to package details (in enrich_package function) for a short ID. See details here: https://github.com/paket-core/mobile/issues/38#issuecomment-424646864

Please update both mobile and JS devs once you are done, so they can start using it.

**Comment by yaroslavr-itd** [comment]
Added in [8e87f60](https://github.com/paket-core/router/commit/8e87f6060b7a7c6c94877692c74b414075fd6790)
