### ISSUE TITLE
Add optional kwargs argument in all event creating endpoints

### ISSUE THREAD

**Issue by israellevin** [paket-core/router#20]
This is very much like the optional photo arg.

Also, please remove leg_price from create_package, it was a mistake - should go in kwargs.

**Comment by yaroslavr-itd** [comment]
Done in [78a65e0](https://github.com/paket-core/router/commit/78a65e008706093eaa9e9bcef7bf3457fe111137), [cbab313](https://github.com/paket-core/router/commit/cbab313dada6fb80494dd1ffb608a173669f1e0b), [027fab6](https://github.com/paket-core/router/commit/027fab66424efcaec5b2d00ad39a42651489877b)
